// <auto-generated />
namespace GestionScolaireAmaSchool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class premier_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(premier_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202503030016428_premier_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
